
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//		Template updated by: Mohammad Ashraful Alam, Microsoft MVP, ASP.NET [admin@ashraful.net]
//		Modification comment: made few items mockable. (03-30-2010)
//			* Made ObjectSet properties of database context as virtual and return type as IObjectSet
//			* Made stored procedure (function import) methods virtual and return type as List<Entity>
//			* Seperate name space for data containers	
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Data.Objects;
using System.Data.EntityClient;
using System.Collections.Generic;//custom-code
using Eisk.BusinessEntities;//custom-code

namespace Eisk.DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseContext object using the connection string found in the 'DatabaseContext' section of the application configuration file.
        /// </summary>
        public DatabaseContext() : base("name=DatabaseContext", "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseContext object.
        /// </summary>
        public DatabaseContext(string connectionString) : base(connectionString, "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseContext object.
        /// </summary>
        public DatabaseContext(EntityConnection connection) : base(connection, "DatabaseContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>..
        /// No Metadata Documentation available.
        /// </summary>
        public virtual IObjectSet<Organism> Organisms//custom-code for testability
        {
            get
            {
                if ((_Organisms == null))
                {
                    _Organisms = base.CreateObjectSet<Organism>("Organisms");
                }
                return _Organisms;
            }
        }
        private ObjectSet<Organism> _Organisms;
    
        /// <summary>..
        /// No Metadata Documentation available.
        /// </summary>
        public virtual IObjectSet<OrganismType> OrganismTypes//custom-code for testability
        {
            get
            {
                if ((_OrganismTypes == null))
                {
                    _OrganismTypes = base.CreateObjectSet<OrganismType>("OrganismTypes");
                }
                return _OrganismTypes;
            }
        }
        private ObjectSet<OrganismType> _OrganismTypes;
    
        /// <summary>..
        /// No Metadata Documentation available.
        /// </summary>
        public virtual IObjectSet<Project_Organisms> Project_Organisms//custom-code for testability
        {
            get
            {
                if ((_Project_Organisms == null))
                {
                    _Project_Organisms = base.CreateObjectSet<Project_Organisms>("Project_Organisms");
                }
                return _Project_Organisms;
            }
        }
        private ObjectSet<Project_Organisms> _Project_Organisms;
    
        /// <summary>..
        /// No Metadata Documentation available.
        /// </summary>
        public virtual IObjectSet<Project> Projects//custom-code for testability
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Organisms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganisms(Organism organism)
        {
            base.AddObject("Organisms", organism);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrganismTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganismTypes(OrganismType organismType)
        {
            base.AddObject("OrganismTypes", organismType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project_Organisms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject_Organisms(Project_Organisms project_Organisms)
        {
            base.AddObject("Project_Organisms", project_Organisms);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }

        #endregion

    }
    

    #endregion

    }//custom-code
    
