//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionProposed
    {
        public ActionProposed()
        {
            this.TreeDetails = new HashSet<TreeDetail>();
        }
    
        public int ActionProposedID { get; set; }
        public string ActionProposedDesc { get; set; }
        public int ColorID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<TreeDetail> TreeDetails { get; set; }
    }
}
