//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Application_Groups = new HashSet<Application_Groups>();
        }
    
        public int ApplicationID { get; set; }
        public string ApplicationName { get; set; }
    
        public virtual ICollection<Application_Groups> Application_Groups { get; set; }
    }
}
