//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.ProjectInfoes = new HashSet<ProjectInfo>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public decimal Lat { get; set; }
        public decimal Lon { get; set; }
        public decimal Y { get; set; }
        public decimal X { get; set; }
    
        public virtual ICollection<ProjectInfo> ProjectInfoes { get; set; }
    }
}
