//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.ActionProposeds = new HashSet<ActionProposed>();
            this.Perimeters = new HashSet<Perimeter>();
        }
    
        public int ColorID { get; set; }
        public string ColorDesc { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<ActionProposed> ActionProposeds { get; set; }
        public virtual ICollection<Perimeter> Perimeters { get; set; }
    }
}
