//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dap
    {
        public int DapID { get; set; }
        public int TreeDetailsID { get; set; }
        public decimal DapValue { get; set; }
    
        public virtual TreeDetail TreeDetail { get; set; }
    }
}
