//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionProposed> ActionProposeds { get; set; }
        public DbSet<Application_Groups> Application_Groups { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Color> Colors { get; set; }
        public DbSet<CommonName> CommonNames { get; set; }
        public DbSet<Condition> Conditions { get; set; }
        public DbSet<Dap> Daps { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<Group_Projects> Group_Projects { get; set; }
        public DbSet<Group_Users> Group_Users { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Notification_User> Notification_User { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Organism> Organisms { get; set; }
        public DbSet<OrganismType> OrganismTypes { get; set; }
        public DbSet<PerimeterPoint> PerimeterPoints { get; set; }
        public DbSet<Perimeter> Perimeters { get; set; }
        public DbSet<Project_Organisms> Project_Organisms { get; set; }
        public DbSet<ProjectInfo> ProjectInfoes { get; set; }
        public DbSet<ProjectInfoTreeLocation> ProjectInfoTreeLocations { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Rep> Reps { get; set; }
        public DbSet<Role_Users> Role_Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ScientificName> ScientificNames { get; set; }
        public DbSet<TermsAndCondition> TermsAndConditions { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<TokenType> TokenTypes { get; set; }
        public DbSet<TreeDetail> TreeDetails { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
