//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_User
    {
        public int NotificationUserID { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
