//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organism
    {
        public Organism()
        {
            this.Project_Organisms = new HashSet<Project_Organisms>();
        }
    
        public int OrganismID { get; set; }
        public int ScientificNameID { get; set; }
        public int CommonNameID { get; set; }
        public int OrganismTypeID { get; set; }
        public int GroupID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatorUserID { get; set; }
        public System.DateTime EditedDate { get; set; }
        public System.Guid EditorUserID { get; set; }
    
        public virtual CommonName CommonName { get; set; }
        public virtual Group Group { get; set; }
        public virtual OrganismType OrganismType { get; set; }
        public virtual ICollection<Project_Organisms> Project_Organisms { get; set; }
        public virtual ScientificName ScientificName { get; set; }
    }
}
