//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganismType
    {
        public OrganismType()
        {
            this.Organisms = new HashSet<Organism>();
        }
    
        public int OrganismTypeID { get; set; }
        public string OrganismTypeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatorUserID { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditorUserID { get; set; }
    
        public virtual ICollection<Organism> Organisms { get; set; }
    }
}
