//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenID { get; set; }
        public int DeviceID { get; set; }
        public System.Guid TokenKey { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> RequestTokenKey { get; set; }
        public int TokenTypeID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual TokenType TokenType { get; set; }
    }
}
