//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenType
    {
        public TokenType()
        {
            this.Tokens = new HashSet<Token>();
        }
    
        public int TokenTypeID { get; set; }
        public string TokenTypeName { get; set; }
    
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
