//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeDetail
    {
        public TreeDetail()
        {
            this.Daps = new HashSet<Dap>();
        }
    
        public int TreeDetailsID { get; set; }
        public int ProjectOrganismID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Height { get; set; }
        public decimal Dap { get; set; }
        public int Dap_Counter { get; set; }
        public Nullable<int> Varas { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<int> ActionProposedID { get; set; }
        public bool Littoral { get; set; }
        public bool MaritimeZone { get; set; }
        public string Commentary { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatorUserID { get; set; }
        public System.DateTime EditedDate { get; set; }
        public System.Guid EditorUserID { get; set; }
    
        public virtual ActionProposed ActionProposed { get; set; }
        public virtual Condition Condition { get; set; }
        public virtual ICollection<Dap> Daps { get; set; }
        public virtual Project_Organisms Project_Organisms { get; set; }
    }
}
