//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL.App_Logic.Entity_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Group_Users = new HashSet<Group_Users>();
            this.Notification_User = new HashSet<Notification_User>();
            this.Role_Users = new HashSet<Role_Users>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsOnLine { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<bool> IsChangePassword { get; set; }
        public Nullable<System.DateTime> LastLockedOutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public Nullable<int> FailedPasswordAnswerAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAnswerAttemptWindowStart { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.Guid CreatorUserID { get; set; }
        public System.DateTime EditedDate { get; set; }
        public System.Guid EditorUserID { get; set; }
    
        public virtual ICollection<Group_Users> Group_Users { get; set; }
        public virtual ICollection<Notification_User> Notification_User { get; set; }
        public virtual ICollection<Role_Users> Role_Users { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
